name: CI
on: [push]
jobs:
  code-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.19.0

      - name: Install deps
        run: pnpm i

      - name: Run checks
        run: pnpm ci
